[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
debug_tool = stlink
upload_protocol = stlink
board_build.mcu = stm32f103c8t6
board_build.f_cpu = 72000000L
build_flags = 
    -DSTM32F103xB
    -I D:\Projects\MareapPowerBoard\STM32TEST\Drivers\OLED
    -Wl,--undefined,_printf_float
    -Wl,--undefined,_printf_scanf
[platformio]
include_dir=Core/Inc
src_dir=Core/Src
lib_dir=Drivers